#!/usr/bin/env bash
set -euo pipefail

# ── Config ──────────────────────────────────────────────────
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="${HOME}/.hermes/plugins/vigil"

echo "==> Creating plugin directory: ${PLUGIN_DIR}"
mkdir -p "${PLUGIN_DIR}"

echo "==> Generating wrapper __init__.py"
cat > "${PLUGIN_DIR}/__init__.py" << WRAPPER
"""
vigil — wrapper auto-generated by install.sh
Delegates to the project __init__.py via runpy.
"""
import runpy
_ns = runpy.run_path("${PROJECT_DIR}/__init__.py")
register = _ns["register"]
WRAPPER

echo "==> Copying plugin.yaml → ${PLUGIN_DIR}"
cp "${PROJECT_DIR}/plugin.yaml" "${PLUGIN_DIR}/plugin.yaml"

echo "==> Copying config.json → ${PLUGIN_DIR}"
if [ -f "${PROJECT_DIR}/config.example.json" ]; then
    cp "${PROJECT_DIR}/config.example.json" "${PLUGIN_DIR}/config.json"
    echo "    (copied from config.example.json; edit ${PLUGIN_DIR}/config.json to customize)"
elif [ -f "${PROJECT_DIR}/config.json" ]; then
    cp "${PROJECT_DIR}/config.json" "${PLUGIN_DIR}/config.json"
else
    cat > "${PLUGIN_DIR}/config.json" << 'CONF'
{
    "enabled": true,
    "title": "Vigil",
    "sound": "default",
    "body_length": 80
}
CONF
    echo "    (default config generated; edit ${PLUGIN_DIR}/config.json to customize)"
fi

echo ""
echo "═══ Vigil installed ═══"
echo "Next: add 'vigil' to ~/.hermes/config.yaml under plugins.enabled, then restart Hermes."
